package com.isc.model;
// Generated Apr 5, 2017 2:34:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Proxy;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", catalog = "my_db", uniqueConstraints = @UniqueConstraint(columnNames = "school_id"))
@Proxy(lazy = false)
public class School implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String schoolId;
	private String schoolName;
	private String address;
	private String contact;
	private Boolean active;

	public School() {
	}

	public School(String schoolId, String schoolName, String address, String contact, Boolean active) {
		this.schoolId = schoolId;
		this.schoolName = schoolName;
		this.address = address;
		this.contact = contact;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "school_id", unique = true, nullable = false, length = 30)
	public String getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(String schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "school_name", nullable = false, length = 50)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact", nullable = false, length = 65535)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "active", nullable = false)
	public Boolean isActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
