package com.isc.model;
// Generated Apr 5, 2017 2:34:38 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Proxy;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "my_db", uniqueConstraints = @UniqueConstraint(columnNames = "subject_id"))
@Proxy(lazy = false)
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String subjectId;
	private String subjectName;
	private float credit;
	private int hour;
	private String description;
	private boolean active;

	public Subject() {
	}

	public Subject(String subjectId, String subjectName, float credit, int hour, String description, boolean active) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.credit = credit;
		this.hour = hour;
		this.description = description;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "subject_id", unique = true, nullable = false, length = 30)
	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subject_name", nullable = false, length = 50)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "credit", nullable = false, precision = 12, scale = 0)
	public float getCredit() {
		return this.credit;
	}

	public void setCredit(float credit) {
		this.credit = credit;
	}

	@Column(name = "hour", nullable = false)
	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
